spring:
  application:
    name: ZoomindAssignment

  data:
    mongodb:
      uri: ${MONGO_URI}

    redis:
      host: ${REDIS_HOST} sion
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      client-type: lettuce
      timeout: 600000
      ssl:
        enabled: true

  cache:
    type: redis

logging:
  level:
    com.example.ZoomindAssignment: DEBUG
    org.springframework: INFO
